In [1]:
class Employee:
    num_employees = 0

    def __init__(self, name, family, salary, department):
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department
        Employee.num_employees += 1

    @staticmethod
    def average_salary(employees):
        total_salary = sum(emp.salary for emp in employees)
        return total_salary / len(employees)

class FulltimeEmployee(Employee):
    def __init__(self, name, family, salary, department, experience):
        super().__init__(name, family, salary, department)
        self.experience = experience

employee1 = Employee("John Doe", "Family A", 60000, "HR")
employee2 = Employee("Jane Smith", "Family B", 75000, "Finance")

fulltime_employee1 = FulltimeEmployee("Alice Johnson", "Family C", 80000, "IT", 3)
fulltime_employee2 = FulltimeEmployee("Bob Williams", "Family D", 90000, "Engineering", 5)

employees = [employee1, employee2, fulltime_employee1, fulltime_employee2]
avg_salary = Employee.average_salary(employees)

print("Total number of employees:", Employee.num_employees)
print("Average salary:", avg_salary)


Total number of employees: 4
Average salary: 76250.0


In [3]:
import numpy as np
random_vector = np.random.uniform(1, 20, size=20)
print("Original array:")
print(random_vector)

reshaped_array = random_vector.reshape(4, 5)

max_indices = np.argmax(reshaped_array, axis=1)

reshaped_array[np.arange(4), max_indices] = 0

print("\nReshaped array:")
print(reshaped_array)


Original array:
[ 2.35104668 13.2579605  18.30664635  1.19127204  2.41996359 13.59967525
 15.27520732 12.29234851  2.14092215  7.62587702 11.64479036 14.07696663
 17.36751437  5.74298434 16.68339783  9.30785615 10.90069013 15.37107566
  4.75717622 19.23561929]

Reshaped array:
[[ 2.35104668 13.2579605   0.          1.19127204  2.41996359]
 [13.59967525  0.         12.29234851  2.14092215  7.62587702]
 [11.64479036 14.07696663  0.          5.74298434 16.68339783]
 [ 9.30785615 10.90069013 15.37107566  4.75717622  0.        ]]
